### ISSUE TITLE
Couldn't match "...Internal.Contains.Contains field (Rep t)" with "Just a"

### ISSUE THREAD

**Issue by mrkgnao** [kcsongor/generic-lens#10]
Consider this:

```haskell
getName :: HasField "name" t a => t -> a
getName = getField @"name"
````

On the latest Stack LTS, with the current master version of `generic-lens`, I get

```
    • Couldn't match type ‘generic-lens-0.2.0.0:Data.Generics.Record.Internal.Contains.Contains
                             "name" (Rep t)’
                     with ‘'Just a’
        arising from a use of ‘getField’
```

and the `Internal` modules are all hidden so I can't even add that constraint myself (suboptimal as it is).
I end up having to replicate the instance constraints for `HasField` in my code. In my use-case this is a default implementation for a class function, so it's not terrible, but I don't understand why resolution fails (i.e. why `HasField` does not imply the `Contains` constraint).

**Comment by kcsongor** [comment]
It seems like your arguments are flipped the other way around - does the following work?
```
getName :: HasField "name" a t => t -> a
getName = getField @"name"
```

`HasField n a s` means that `s` has a field with name `n` and type `a`, perhaps this fact should be better documented, as the ordering may be unintuitive, but this is what works best with type applications and partial application.
