### ISSUE TITLE
Type application fails in ghc-8.8.1

### ISSUE THREAD

**Issue by newhoggy** [kcsongor/generic-lens#100]
When compiling with `ghc-8.8.1` the following code fails to compile:

```
opts ^. the @"indexType"
```

It results in the following error:

```

app/App/Commands/Build.hs:28:35: error:
    • Expected a type, but
      ‘"indexType"’ has kind
      ‘ghc-prim-0.5.3:GHC.Types.Symbol’
    • In the type ‘"indexType"’
      In the second argument of ‘(^.)’, namely ‘the @"indexType"’
      In the expression: opts ^. the @"indexType"
   |
28 | runBuild opts = case opts ^. the @"indexType" of
   |                                   ^^^^^^^^^^^
```

The same code compiles on earlier versions of GHC including `ghc-8.2.2`, `8.4.2`, and `8.6.5`.

The code is trying to access the field in this datatype:

```
newtype BuildOptions = BuildOptions
  { indexType :: IndexType
  } deriving (Eq, Show, Generic)
```

I use the following extensions:

```
{-# LANGUAGE DataKinds        #-}
{-# LANGUAGE TypeApplications #-}
```

**Comment by phadej** [comment]
That's fixed in https://github.com/kcsongor/generic-lens/pull/98

**Comment by kcsongor** [comment]
Thanks @newhoggy for reporting this! As @phadej said, this has been fixed - I'm making a release now.

**Comment by kcsongor** [comment]
Version `1.2.0.1` includes the fix for this now
