### ISSUE TITLE
OverloadedRecordLabels

### ISSUE THREAD

**Issue by duog** [kcsongor/generic-lens#11]
Hi, I think your library is really cool.

I did some hacking this morning and came up with this:
https://github.com/duog/generic-lens/commit/f3b74c35d699a59ee2f337c0027a0fd3370c3de5

Which allows one to write `#age` to mean `(HasField "age" a s) => Lens' s a`, which I think is pretty slick. Would you be interested in adding something like this?

I would like it if this library could support type-changing lenses and prisms, and provide isomorphsims when possible. Do you think that's feasible?

**Comment by kcsongor** [comment]
Hi, that's pretty slick indeed! I would be happy to add that feature in.

The proposal in your `Labels` module also sounds interesting, I wonder if you've seen the [Data.Generics.Product.Any](https://github.com/kcsongor/generic-lens/blob/master/src/Data/Generics/Product/Any.hs) lens (and the corresponding prism for `Sum`s)? It picks the lens based on the kind of the applied type parameter, but if I understand correctly, your idea is to use the shape of the data to decide the meaning of the label?

I have been thinking about adding type-changing lenses and prisms, and I think they shouldn't be very hard to implement, probably using the `Generic1` instances to get an idea of where the parameters are in the structure.

Providing `Iso`s (and even `Traversal`s in certain other cases) I think should also be possible, and it's certainly something I would like to add.

**Comment by duog** [comment]
I have seen that module.

I'd like the shape of the data to determine whether an optic is type-changing, and whether it should be an (IndexPreserving)Iso(') or an (IndexPreserving)Traversal('). 

I'd like the shape of the label to determine whether it should be a Prism('), "field optic", "position optic", or  "type optic". I don't know exactly how one would do the required type level parsing. I imagine
#fieldName
#_1
#_Left
would be examples, I don't know how one would do "type optics".

I'm using the labels in a current project, I'll get back to you to let you know how unbearable the type inference and error messages are.

**Comment by mpickering** [comment]
A big problem with using `IsLabel` is that you get orphan instances. A few anonymous records libraries already define orphans for `(->)` and `Proxy` which means that if you ever depend on both of them, `#` becomes unusable.

**Comment by duog** [comment]
Yes, the orphan instances are gross. This is really just a toy.

I've decided to just push it as a separate library, https://github.com/duog/generic-lens-labels

**Comment by kcsongor** [comment]
OK, that is probably the right call. Thanks
