### ISSUE TITLE
Roadmap required

### ISSUE THREAD

**Issue by thepratt** [kcsongor/generic-lens#12]
Where on the roadmap is the PHP backend?
Not being able to run this lib within PHP is really blocking my workflow.

**Comment by i-am-tom** [comment]
+1, can reproduce this issue

**Comment by kcsongor** [comment]
I couldn't reproduce this with the latest version

**Comment by i-am-tom** [comment]
Is this a WONTFIX?

**Comment by thepratt** [comment]
Reopen pls
