### ISSUE TITLE
Revert #120

### ISSUE THREAD

**Issue by arybczak** [kcsongor/generic-lens#126]
We're close to merging https://github.com/well-typed/optics/pull/361 that'll get rid of visible `GeneralLabelOptic`. Reasons:
- Pluggable incoherence leads to confusion
- Field/position lenses from this library are not as efficient at compile time as they could be, which makes them not optimal for use in production

The above PR is based on bits from this library and significantly improves compilation time efficiency of generic field/position lenses (and improves the user experience as there's only one variant of each, not 3).

This is a heads-up as if the PR ends up being merged, support for overloaded labels in `generic-optics` will have to be reverted.

In any case, people are welcome to backport the efficiency/usability improvements from the PR to `generic-lens-core`.

**Comment by kcsongor** [comment]
Thanks for the heads up!

After a long hiatus, I'm returning to working on generic-lens, there is a large pile of things that I'm currently trying to catch up on, and I apologise for having left a lot of your helpful contributions languish.

As a first step, I'm going to make a minor release to clear the backlog of the patches that haven't been published to hackage yet, and I see that #120 is one of them. To clarify, this feature is no longer compatible with `optics`, right? I'm going to remove it then, and take it from there.

I will also be looking at the improvements you made there and try to backport them.

Thanks again.

**Comment by arybczak** [comment]
> To clarify, this feature is no longer compatible with optics, right?

Correct.

> I will also be looking at the improvements you made there and try to backport them.

FYI https://github.com/well-typed/optics/pull/391 has comparisons you might be interested in.

**Comment by michaelpj** [comment]
It was reverted
