### ISSUE TITLE
Performance guarantees?

### ISSUE THREAD

**Issue by nomeata** [kcsongor/generic-lens#13]
At the IFL talk, @kcsongor mentioned that these generic lenses optimize down to what one would write by hand. That would be amazing, but I cannot reproduce it. Here is my example:

```
{-# LANGUAGE RankNTypes, DeriveGeneric, TypeApplications, DataKinds #-}
module GenericLens where

import GHC.Generics
import Data.Generics.Product

data Record = MkRecord { fieldA :: Int
                       , fieldB :: Bool
                       } deriving Generic

type Lens' s a = forall f. Functor f => (a -> f a) -> s -> f s

fieldALensManual :: Lens' Record Int
fieldALensManual f (MkRecord a b) = (\a -> MkRecord a b) <$> f a

fieldALensGeneric :: Lens' Record Int
fieldALensGeneric = field @"fieldA"
```

I compile this with
```
ghc-8.2 -O2 GenericLens.hs  -ddump-simpl
```
and I get somewhat nice Core for the manual lens:
```
fieldALensManual
  = \ (@ (f_a5HR :: * -> *))
      ($dFunctor_a5HT :: Functor f_a5HR)
      (f1_a1Th :: Int -> f_a5HR Int)
      (ds_d6PM :: Record) ->
      case ds_d6PM of { MkRecord a_a1Ti b_a1Tj ->
      fmap
        @ f_a5HR
        $dFunctor_a5HT
        @ Int
        @ Record
        (\ (a1_a1Tk :: Int) -> GenericLens.MkRecord a1_a1Tk b_a1Tj)
        (f1_a1Th a_a1Ti)
      }
```
but very large Core for the generic lens, which I will not even paste here. But there is a lot of stuff about Generics still around.

Under what conditions, if any, do the generic lenses optimize to the “real” thing?

**Comment by nomeata** [comment]
Ok, looking at the paper it seems that adding `ravel` should make the Core the same. But I cannot confirm this either, using this code:
```
{-# LANGUAGE RankNTypes, DeriveGeneric, TypeApplications, DataKinds, ExistentialQuantification#-}
module GenericLens where

import GHC.Generics
import Data.Generics.Product

data Record = MkRecord { fieldA :: Int
                       , fieldB :: Bool
                       } deriving Generic

type Lens' s a = forall f. Functor f => (a -> f a) -> s -> f s

fieldALensManual :: Lens' Record Int
fieldALensManual f (MkRecord a b) = (\a -> MkRecord a b) <$> f a

fieldALensGeneric :: Lens' Record Int
fieldALensGeneric = field @"fieldA"

fieldALensGenericYoneda :: Lens' Record Int
fieldALensGenericYoneda = ravel (field @"fieldA")

data Coyoneda f b = forall a. Coyoneda (a -> b) (f a)

instance Functor (Coyoneda f) where
    fmap f (Coyoneda g fa) = Coyoneda (f . g) fa

inj :: Functor f => Coyoneda f a -> f a
inj (Coyoneda f a) = fmap f a

proj :: Functor f => f a -> Coyoneda f a
proj fa = Coyoneda id fa

ravel :: Functor f => ((a -> Coyoneda f b) -> (s -> Coyoneda f t))
                   -> (a -> f b) -> (s -> f t)
ravel coy f s = inj $ coy (\a -> proj (f a)) s
```

**Comment by mpickering** [comment]
Hi Joachim, 

After making such a claim in the talk, I tried it out again and indeed with the most recent version of the library the situation is worse and the generated core is different. I just tried it again with an older version, and I see what is claimed with the paper. 

@kcsongor What have you changed since about the 0.2 version? The precise commit is in the paper repo.

**Comment by kcsongor** [comment]
I'm investigating this regression and will try to get back later today

**Comment by nomeata** [comment]
Heh. At least a good story for me to advocate for “optimization unit tests” that I envision :-)

**Comment by kcsongor** [comment]
Managed to track down the origin of the regression, now looking into integrating ghc-proofs into the test suite!

**Comment by nomeata** [comment]
Not sure if `ghc-proofs` is already up to that, in terms of usability. But let me know how it went, and what you need! Or corner me at ICFP.

**Comment by kcsongor** [comment]
I was looking at the core by hand and GHC indeed recognises the equivalence by rewriting to a `generic = handwritten`  form - my understanding is that this is exactly what ghc-proofs is looking for?

**Comment by nomeata** [comment]
Oh yes, more or less! But I meant that `ghc-proofs` has not been used by anyone but me so far :-)

**Comment by nomeata** [comment]
With this patch to `ghc-proofs` I can prove the desired equation:
```
diff --git a/GHC/Proof/Plugin.hs b/GHC/Proof/Plugin.hs
index 0527f70..2d6076d 100644
--- a/GHC/Proof/Plugin.hs
+++ b/GHC/Proof/Plugin.hs
@@ -128,6 +128,8 @@ simplify guts more_in_scope expr = do
                         >>= simplExpr (simplEnv in_scope 2) . occurAnalyseExpr
                         >>= simplExpr (simplEnv in_scope 1) . occurAnalyseExpr . cseOneExpr'
                         >>= simplExpr (simplEnv in_scope 1) . occurAnalyseExpr . cseOneExpr'
+                        >>= simplExpr (simplEnv in_scope 0) . occurAnalyseExpr . cseOneExpr'
+                        >>= simplExpr (simplEnv in_scope 0) . occurAnalyseExpr . cseOneExpr'
     return expr'
 
 #if  __GLASGOW_HASKELL__ >= 801
```
The reason I was not doing that so far is that it makes it harder to understand the printed code when an equation does _not_ hold – (e.g. “foldl” instead of explicit lists.) But it really is the right thing to do – and with it, more of HLint’s equations can be proven!

I have just uploaded `ghc-proofs-0.1.1` to hackage, please try again!

**Comment by kcsongor** [comment]
Great, the test suite now includes several examples using `ghc-proofs` - thanks!

**Comment by 3noch** [comment]
Is there a writeup of this amazing work? I think a lot of folks on the usual social channels (Reddit, etc.) would love to know about this.
