### ISSUE TITLE
Issues with large tuples

### ISSUE THREAD

**Issue by andreasewering** [kcsongor/generic-lens#131]
Hi,
first of all thanks for the incredible library.
I would like to be able to get values from large tuples (8+) by their types, but currently it seems like

```
data SomeRecord = {
    fieldA :: A,
    fieldB :: B
  }

extractTwo :: (HasType A a, HasType B a) => a -> SomeRecord
extractTwo a = SomeRecord (getTyped a) (getTyped a)
```

works for tuples up to size 7 containing both A and B, but fails with a confusing error message
for larger sized tuples. 

My use case for this is working with the postgresql-typed library, where the results of queries are represented as tuples.
I want to do a single query for a couple of fields and do not want to worry about the exact row tuple type in my business logic.

It would be great if you could hint me how to create the missing instances myself or suggest a different solution :)

**Comment by andreasewering** [comment]
Looking closer I think the problem is that GHC.Generics does not include Generic Instances for tuples of size >7.

**Comment by phadej** [comment]
You may want to ping on https://gitlab.haskell.org/ghc/ghc/-/issues/16699

**Comment by andreasewering** [comment]
@phadej Interesting, I should then probably look out for performance issues.

I'm closing this, since it has nothing to do with generic lens. The issue was fixed by adding orphan generic instances 

`deriving instance Generic ((,,,,,,,) a b c d e f g h)
deriving instance Generic ((,,,,,,,,) a b c d e f g h i) `
