### ISSUE TITLE
generic-lens allows modification of private data structures

### ISSUE THREAD

**Issue by debug-ito** [kcsongor/generic-lens#142]
Hi. I'm new to generic-lens. When I tried generic-lens-2.2.0.0, I found that it allowed modification of private data structures, that is, data types whose data constructor is not exposed.

For example, suppose you have module A.

```haskell
module A (Private, newPrivate) where

import GHC.Generics (Generic)

-- | The data constructor is not exposed.
data Private = Private { foo :: Int } deriving (Show,Generic)

-- | A smart constructor
newPrivate :: Int -> Private
newPrivate = Private
```

and module Main, that uses module A.

```haskell
module Main (main) where

import A (Private, newPrivate)
import Data.Generics.Product (HasField(..))
import Lens.Micro.Platform ((.~))

main :: IO ()
main = putStrLn $ show $ (field @"foo" .~ 10) $ newPrivate 5
```

The above code compiles without error. (well, I didn't try the above exact code, but did try similar one..)

The intension of module A can be to limit possible operations on `Private` type to protect its integrity. So, if generic-lens would respect that protection, it would be much safer, I think.

Is this behavior intensional for generic-lens? Am I missing something? Is there any workaround or best practices?

**Comment by mpickering** [comment]
The problem is that you expose the representation by deriving a `Generic` instance. If you want to make it hidden then you can't have the instance.

**Comment by kcsongor** [comment]
That's right, deriving a `Generic` instance (which automatically gets exported, no way to hide it) exposes the internal structure of your type. For example, it also makes it possible to derive a `FromJSON` instance outside of the module.

There's no general workaround, but you could for example stop the `field` lens from working by writing something like
```hs
import GHC.TypeLits
...
instance TypeError ('Text "Illegal") => HasField' Private "foo" Int
```

**Comment by debug-ito** [comment]
Thanks for explanation! So, if I REALLY want to hide internal of the type `Private`, I shouldn't have derived `Generic` instance in the first place.

Thanks also for the technique using `TypeError`. That looks like magic to me.

**Comment by adamgundry** [comment]
> deriving a `Generic` instance (which automatically gets exported, no way to hide it) exposes the internal structure of your type

I wonder... would it make sense to change `Generic` instances to be visible only if a data constructor from the type is in scope, more or less like `Coercible` does for newtypes? That would allow representation hiding like this. Of course it would be a massively breaking change though.

Or perhaps it could be an option at the instance declaration/deriving site for it to have this property, e.g.
```hs
data Private = Private { foo :: Int } deriving private Generic

deriving instance private Show Private

instance private Eq Private where ...
```

**Comment by kcsongor** [comment]
@adamgundry that's an interesting idea. Another option could be something along the lines of
```hs
module Foo (...) hiding (Generic Private, Show Private) where
```

**Comment by debug-ito** [comment]
According to [GHC manual](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/hasfield.html), [GHC.Records.HasField](https://hackage.haskell.org/package/base-4.16.0.0/docs/GHC-Records.html) typeclass constraint is solved depending on the visibility of the target field.

**Comment by phadej** [comment]
@adamgundry 

> I wonder... would it make sense to change Generic ...!

but `Generic` is an ordinary class, like `Eq` or `Ord`; GHC just knows how to derive it, but sometimes it is written by hand!

A change so `Generic` would be more like `HasField`, so GHC would automatically derive it at use-site if the data constructors are visible would be... interesting.

**Comment by adamgundry** [comment]
Thanks for the comments. I like the idea of marking instance declaration sites, so I've raised a ticket suggesting it here: https://github.com/ghc-proposals/ghc-proposals/issues/483

@kcsongor Hiding instances in the module header does seem possible, and is more flexible, but I think it would be easy for instances to accidentally leak out via an internal module that neglected to blacklist them.

**Comment by adamgundry** [comment]
> > I think it would be easy for instances to accidentally leak out via an internal module that neglected to blacklist them.
> 
> This is a good point, but I think a similar argument applies to constructor hiding in that the module's author has to take extra care.

Well, the advantage of relying on constructor hiding is that it is already established as the way in which types are made abstract, so many libraries already do this.

> Another (but more breaking and perhaps less intuitive) version of this could be if GHC refused to automatically export instances whose derived code uses a constructor that's not exported. This would mean that `Generic`, `Read`, and `FromJSON` for example would require explicit exporting if the type's constructor is hidden, but `Show` and `ToJSON` would not (since these only pattern match, but don't construct). This would be in line with `Coercible`'s behaviour.

Hmm, I would consider pattern-matching on an abstract type to also be breaking the abstraction, although I can see it is a little less problematic for some use cases (e.g. where a smart constructor enforces an invariant on construction only).

My inclination is that a gradual change (i.e. allow instances to be "private" where explicitly requested) is better than widespread breakage due to changing the default, although I suppose we could have a language extension control the default.
