### ISSUE TITLE
Make use of unrestricted `OverloadedLabels`

### ISSUE THREAD

**Issue by amesgen** [kcsongor/generic-lens#151]
The [Unrestricted `OverloadedLabels` proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0170-unrestricted-overloadedlabels.rst), implemented in GHC 9.6, enables things like `#Constructor` or `#123`.

This would enable things like

 - Support constructor prisms with the `_` prefix (done in #152)
 - Further shortcuts, such as `#3` for `position @3`.

This should be implementable in a backwards-compatible way, but it should be easier when using `UnconsSymbol` from GHC 9.2. WDYT?

**Comment by kcsongor** [comment]
Reopening since the positional `#3` would also be nice to have
