### ISSUE TITLE
Use OverloadedLabels?

### ISSUE THREAD

**Issue by 3noch** [kcsongor/generic-lens#16]
Could `OverloadedLabels` offer a lighter weight syntax to this brilliant API?

**Comment by glaebhoerl** [comment]
One problem is that uppercase labels are not currently allowed, which excludes prisms. https://ghc.haskell.org/trac/ghc/ticket/11671?cversion=0&cnum_hist=8

**Comment by kcsongor** [comment]
For lenses yes, and in fact, it isn't even very difficult to define these labels. However, doing so would require writing orphan instances for `->`. Some other libraries already do that for various reasons, and having these instances overlap would be terrible. There was some discussion about this: https://github.com/kcsongor/generic-lens/issues/11, and ultimately decided not to include it in the library.
I often end up just throwing in the instance in my projects when I need the nicer syntax.

**Comment by 3noch** [comment]
Aha! I wondered if this had already been considered. Perhaps a note in the README about this discussion would be helpful.

**Comment by Lysxia** [comment]
It could also go in a module that may be fine for end-user applications to import and for people to experiment with. That would also be a natural place to explain to library writers why they should probably avoid it.

**Comment by mpickering** [comment]
There is already the [generic-lens-labels](https://github.com/duog/generic-lens-labels) library but I strongly suggest that using it in a library is a bad idea!

**Comment by 3noch** [comment]
Looks like this has been addressed!
