### ISSUE TITLE
Feature Request: Get term-level field names / positions

### ISSUE THREAD

**Issue by 3noch** [kcsongor/generic-lens#17]
It could be convenient at times to convert type-safe field names into term level strings and type safe positions into term level integers, possibly for display or serialization.

**Comment by kcsongor** [comment]
I don't think I quite understand what you mean, could you give an example of how this would be used?

**Comment by 3noch** [comment]
I'm toying with the idea of having my GHCJS front-end send the names of fields to the back end so that it can use them for ordering or whathaveyou. I'm hoping that I can piggy back on `generic-lens` to prove that some `Symbol` exists in my record before sending that field name / index over the wire. The backend would then lift that name/index back up somehow and allow me to do generic operations in a type safe way.

**Comment by kcsongor** [comment]
I see now, thanks for the explanation.
Currently, I can't think of a nice way of doing this: getting a list of field names is not very difficult to do, since all of that information is available in `GHC.Generic`. However, going in the other direction is more difficult.

The biggest issue is that when I get a string, I have no way of recovering the type information of the field that the string corresponds to.
```
getLens :: String -> Lens' s ???
```
The best we could do here is to existentially quantify the field type, and wrap that in a data type, something like

```
data SomeLens s = forall a. SomeLens (Lens' s a)
```

And then try something like

```
getLens :: String -> Maybe (SomeLens s)
```

But even then, our existential removes all information about the type, so we would probably have to store some additional dictionary to be able to do something useful with them.
Overall, this could work, but the more I think about it the more I feel that this would be a very invasive change.
If you have a better idea though, I would be happy to discuss!

**Comment by 3noch** [comment]
Ah, yes that's a bit more ambitious than what I was going for. I don't need to recover a fully row-polymorphic lens back from the term-level string. I can supply the record to "search" for the given field name. If the field name exists, I can then recover the lens.

**Comment by 3noch** [comment]
My interest here is primarily from going to `Symbol` to `String` after checking that the symbol does indeed exist in some known record type. Perhaps this is easy enough that it doesn't require any change to `generic-lens` at all. I don't know much about TypeLits.

**Comment by kcsongor** [comment]
Something like this?

```haskell
fieldName :: forall field s a. (KnownSymbol field, HasField field s a) => String
fieldName = symbolVal (Proxy @field)
```

```
data T = T { field1 :: Int, field2 :: String } deriving Generic

>>> fieldName @"field1" @T
"field1"
>>> fieldName @"field2" @T
"field2"
>>> fieldName @"field3" @T

<interactive>:110:1: error:
    • The type T does not contain a field named "field3"
    • In the expression: fieldName @"field3" @T
      In an equation for ‘it’: it = fieldName @"field3" @T
```

**Comment by 3noch** [comment]
Ha! Yes. Yes indeed. That is easy!

In that case allow me to propose another idea: A way to get the *index* (at the value level) of a `Symbol`. That would be a more efficient method of encoding the data.

**Comment by smaccoun** [comment]
Is there a way to somehow case over the available fields for a given record? Looking at the above, I could get the field name and case over that, but I'd get something like:

```haskell
data Foo = Foo {f1 :: String, f2 :: Int}

doSomethingWithField :: :: forall field s a. (KnownSymbol field, HasField field Foo a) -> Proxy field => String
doSomethingWithField pField =
  case symbolVal pField of
     "f1" -> doSomethingGivenF1
     "f2" -> doSomethingGivenF2
     _ -> notNeededButNeedToDoSomething
```

But doing this of course requires the unnecessary default case check.
Of course the dream for me would be to be able to write something like:

```haskell
data Foo = Foo {f1 :: String, f2 :: Int}

doSomethingWithField :: :: forall field s a. (KnownSymbol field, HasField field Foo a) -> Proxy field => String
doSomethingWithField @"f1" =  doSomethingGivenF1
doSomethingWithField @"f2" =  doSomethingGivenF2
```

My guess was using typeclasses was the easiest solution. Here's a simple one where I just assume some kind of string is generated based on the field passed in

```
class WithFooField f where
  withFooField :: Text

instance WithFooField (Proxy "f1") where
  withFooField = "you are using the f1 field"
```

Or perhaps the best way is to map the fields with a GADT? I know I'm essentially trying to do some kind of reflection, but  not sure how to do this.

Not sure if I should write this as a separate issue, but I have a good use case for this and was wondering if it's possible
