### ISSUE TITLE
Should `projectSub` have type `sup -> Maybe sub`?

### ISSUE THREAD

**Issue by louispan** [kcsongor/generic-lens#21]
Is there a reason why the type of `projectSub :: sup -> Either sup sub`?
I could be missing something, but wouldn't the left part of the final value always be the input `sup`?
Using a Maybe will also be more consistent with `AsType` `projectTyped :: s -> Maybe a`

**Comment by kcsongor** [comment]
Thanks for pointing this out, the actual reason why it's an `Either` is that it's used directly in the construction of the prism, which expects an `Either`, but this is not a good reason to make it to the public API, and it would be better to make these consistent across the classes.

**Comment by louispan** [comment]
Awesome. I'm glad you don't mind making changes to make things more consistent.
