### ISSUE TITLE
Is it possible to support "monadic" field/typed records?

### ISSUE THREAD

**Issue by louispan** [kcsongor/generic-lens#23]
Merry Xmas! I hope this is the correct place to ask questions about generic-lens, but when you have time after the holidays, would you mind answering if generic-lens supports "monadic" fields?

Given the definition of `Foo` below

    data Foo m s = Foo
      { foo1 :: m s
      , foo2 :: [s]
      } deriving G.Generic

The following compiles ok

    modifyFoo1 :: Foo Identity Int -> Foo Identity Int
    modifyFoo1 x = x & field @"foo1" .~ (pure 1)

But the following has the below compile error (I have also tried with NoMonomorphismRestriction)
 
    modifyFoo2 :: Applicative m => Foo m Int -> Foo m Int
    modifyFoo2 x = x & field @"foo1" .~ (pure 1)

GHC 8.2.2 compile error

    error:
        • Couldn't match type ‘generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.Infer'
                                 (Foo
                                    m
                                    (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.P
                                       0 Int))
                                 (m (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.P
                                       0 Int))
                                 (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.PSub
                                    (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.Unify
                                       (m (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.P
                                             0 Int))
                                       (m Int)))
                                 (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.PickTv
                                    (m (generic-lens-0.5.0.0:Data.Generics.Internal.Families.Changing.P
                                          0 Int))
                                    (m Int))’
                         with ‘'(Foo m Int, m Int)’
            arising from a use of ‘field’
        • In the first argument of ‘(.~)’, namely ‘field @"foo1"’
          In the second argument of ‘(&)’, namely ‘field @"foo1" .~ (pure 1)’
          In the expression: x & field @"foo1" .~ (pure 1)
        • Relevant bindings include
            x :: Foo m Int
              (bound at src/Glazier/React/Prototypes/Listing/Internal.hs:94:12)
            modifyFoo2 :: Foo m Int -> Foo m Int
              (bound at src/Glazier/React/Prototypes/Listing/Internal.hs:94:1)
       |
    94 | modifyFoo2 x = x & field @"foo1" .~ (pure 1)
       |                    ^^^^^^^^^^^^^

**Comment by kcsongor** [comment]
Merry Christmas!
Thanks for reporting this, what you described is actually a bug in the type family that infers which type parameters can be changed by a lens. It currently (wrongly) assumes that type parameters are of kind *.

I think I have a fix, I'll see if that works.

**Comment by louispan** [comment]
Thank you. I'm only using this feature for my personal project, so no rush, enjoy your holidays first. Unless you are like me and think "What better way to spend some extra time during the holidays than haskelling?"

**Comment by kcsongor** [comment]
I believe this should be fixed, I'll make a new release later today, thanks again.

**Comment by louispan** [comment]
Thank you for the quick fix. I just tried 0.5.1.0 and it works :)
