### ISSUE TITLE
Should HasType a a typecheck?

### ISSUE THREAD

**Issue by Jhana1** [kcsongor/generic-lens#34]
```
λ> newtype K = K { getK :: Int } deriving (Generic)
λ> getTyped :: K -> K

<interactive>:82:1: error:
    • The type K does not contain a value of type K
    • In the expression: getTyped :: K -> K
      In an equation for ‘it’: it = getTyped :: K -> K
```
Considering K is a K would an instance work something like so?
```
import Control.Lens (iso)

instance {-# OVERLAPS #-} HasType a a where
  typed = iso id id
  getTyped = id
  setTyped = const 
```

I don't have any experience around overlapping instances or solving related issues, but I think this seems pretty clean.

**Comment by kcsongor** [comment]
I thought about this, but the problem is that now we lose the ability to focus on self-referential types:
```
data K = K Int K
```

I agree that the identity would be the intuitive behaviour in some use-cases. For those, I usually define a specialised class with the overlapping instance.

**Comment by Jhana1** [comment]
The identity in the self referential case definitely breaks the law of least surprises. Thanks for the advice, I'll continue to use a specialised case as necessary.

Cheers
