### ISSUE TITLE
Example doesn't build

### ISSUE THREAD

**Issue by k-bx** [kcsongor/generic-lens#36]
Hi. The example code doesn't build for me. Here's a repo which reproduces the issue and also the errors are shown in the README https://github.com/k-bx/generic-lens-example

Thank you!

**Comment by kcsongor** [comment]
Hi, thanks for reporting this!

The example module has indeed been updated to reflect some internal changes in the library, which have not been released yet. It should build with the library compiled from `master`. That said, a new release is in order soon, and I'll do it as soon as I can!
