### ISSUE TITLE
Test suite failures with 1.0.0.0

### ISSUE THREAD

**Issue by snoyberg** [kcsongor/generic-lens#43]
Below is the full output from the Stackage build server:

<details>
> /tmp/stackage-build11/generic-lens-1.0.0.0$ ghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup
> /tmp/stackage-build11/generic-lens-1.0.0.0$ ./Setup configure --enable-tests --package-db=clear --package-db=global --package-db=/var/stackage/work/builds/nightly/pkgdb --libdir=/var/stackage/work/builds/nightly/lib --bindir=/var/stackage/work/builds/nightly/bin --datadir=/var/stackage/work/builds/nightly/share --libexecdir=/var/stackage/work/builds/nightly/libexec --sysconfdir=/var/stackage/work/builds/nightly/etc --docdir=/var/stackage/work/builds/nightly/doc/generic-lens-1.0.0.0 --htmldir=/var/stackage/work/builds/nightly/doc/generic-lens-1.0.0.0 --haddockdir=/var/stackage/work/builds/nightly/doc/generic-lens-1.0.0.0
Configuring generic-lens-1.0.0.0...
> /tmp/stackage-build11/generic-lens-1.0.0.0$ ghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb Setup
> /tmp/stackage-build11/generic-lens-1.0.0.0$ ./Setup build
Preprocessing test suite 'examples-doctests' for generic-lens-1.0.0.0..
Building test suite 'examples-doctests' for generic-lens-1.0.0.0..
[1 of 1] Compiling Main             ( examples/doctest.hs, dist/build/examples-doctests/examples-doctests-tmp/Main.o )
Linking dist/build/examples-doctests/examples-doctests ...
Preprocessing test suite 'doctests' for generic-lens-1.0.0.0..
Building test suite 'doctests' for generic-lens-1.0.0.0..
[1 of 1] Compiling Main             ( test/doctest.hs, dist/build/doctests/doctests-tmp/Main.o )
Linking dist/build/doctests/doctests ...
Preprocessing library for generic-lens-1.0.0.0..
Building library for generic-lens-1.0.0.0..
[ 1 of 36] Compiling Data.Generics.Internal.Families.Changing ( src/Data/Generics/Internal/Families/Changing.hs, dist/build/Data/Generics/Internal/Families/Changing.o )
[ 2 of 36] Compiling Data.Generics.Internal.GenericN ( src/Data/Generics/Internal/GenericN.hs, dist/build/Data/Generics/Internal/GenericN.o )
[ 3 of 36] Compiling Data.Generics.Internal.Profunctor.Iso ( src/Data/Generics/Internal/Profunctor/Iso.hs, dist/build/Data/Generics/Internal/Profunctor/Iso.o )
[ 4 of 36] Compiling Data.Generics.Internal.Profunctor.Lens ( src/Data/Generics/Internal/Profunctor/Lens.hs, dist/build/Data/Generics/Internal/Profunctor/Lens.o )
[ 5 of 36] Compiling Data.Generics.Internal.Profunctor.Prism ( src/Data/Generics/Internal/Profunctor/Prism.hs, dist/build/Data/Generics/Internal/Profunctor/Prism.o )
[ 6 of 36] Compiling Data.Generics.Internal.VL.Iso ( src/Data/Generics/Internal/VL/Iso.hs, dist/build/Data/Generics/Internal/VL/Iso.o )
[ 7 of 36] Compiling Data.Generics.Internal.VL.Lens ( src/Data/Generics/Internal/VL/Lens.hs, dist/build/Data/Generics/Internal/VL/Lens.o )
[ 8 of 36] Compiling Data.Generics.Internal.VL.Prism ( src/Data/Generics/Internal/VL/Prism.hs, dist/build/Data/Generics/Internal/VL/Prism.o )
[ 9 of 36] Compiling Data.Generics.Internal.VL.Traversal ( src/Data/Generics/Internal/VL/Traversal.hs, dist/build/Data/Generics/Internal/VL/Traversal.o )
[10 of 36] Compiling Data.Generics.Internal.Void ( src/Data/Generics/Internal/Void.hs, dist/build/Data/Generics/Internal/Void.o )
[11 of 36] Compiling Data.Generics.Product.Internal.Constraints ( src/Data/Generics/Product/Internal/Constraints.hs, dist/build/Data/Generics/Product/Internal/Constraints.o )
[12 of 36] Compiling Data.Generics.Product.Constraints ( src/Data/Generics/Product/Constraints.hs, dist/build/Data/Generics/Product/Constraints.o )
[13 of 36] Compiling Data.Generics.Product.Internal.List ( src/Data/Generics/Product/Internal/List.hs, dist/build/Data/Generics/Product/Internal/List.o )

src/Data/Generics/Product/Internal/List.hs:44:1: warning: [-Wunused-imports]
    The import of ‘Data.Semigroup’ is redundant
      except perhaps to import instances from ‘Data.Semigroup’
    To import instances alone, use: import Data.Semigroup()
   |
44 | import Data.Semigroup
   | ^^^^^^^^^^^^^^^^^^^^^
[14 of 36] Compiling Data.Generics.Product.Internal.Keyed ( src/Data/Generics/Product/Internal/Keyed.hs, dist/build/Data/Generics/Product/Internal/Keyed.o )
[15 of 36] Compiling Data.Generics.Internal.Families.Has ( src/Data/Generics/Internal/Families/Has.hs, dist/build/Data/Generics/Internal/Families/Has.o )
[16 of 36] Compiling Data.Generics.Internal.Families.Collect ( src/Data/Generics/Internal/Families/Collect.hs, dist/build/Data/Generics/Internal/Families/Collect.o )
[17 of 36] Compiling Data.Generics.Internal.Families ( src/Data/Generics/Internal/Families.hs, dist/build/Data/Generics/Internal/Families.o )
[18 of 36] Compiling Data.Generics.Product.Fields ( src/Data/Generics/Product/Fields.hs, dist/build/Data/Generics/Product/Fields.o )
[19 of 36] Compiling Data.Generics.Product.Internal.Positions ( src/Data/Generics/Product/Internal/Positions.hs, dist/build/Data/Generics/Product/Internal/Positions.o )
[20 of 36] Compiling Data.Generics.Product.Internal.Subtype ( src/Data/Generics/Product/Internal/Subtype.hs, dist/build/Data/Generics/Product/Internal/Subtype.o )
[21 of 36] Compiling Data.Generics.Product.List ( src/Data/Generics/Product/List.hs, dist/build/Data/Generics/Product/List.o )
[22 of 36] Compiling Data.Generics.Product.Param ( src/Data/Generics/Product/Param.hs, dist/build/Data/Generics/Product/Param.o )
[23 of 36] Compiling Data.Generics.Product.Positions ( src/Data/Generics/Product/Positions.hs, dist/build/Data/Generics/Product/Positions.o )
[24 of 36] Compiling Data.Generics.Product.Subtype ( src/Data/Generics/Product/Subtype.hs, dist/build/Data/Generics/Product/Subtype.o )
[25 of 36] Compiling Data.Generics.Product.Typed ( src/Data/Generics/Product/Typed.hs, dist/build/Data/Generics/Product/Typed.o )
[26 of 36] Compiling Data.Generics.Product.Any ( src/Data/Generics/Product/Any.hs, dist/build/Data/Generics/Product/Any.o )
[27 of 36] Compiling Data.Generics.Product.Types ( src/Data/Generics/Product/Types.hs, dist/build/Data/Generics/Product/Types.o )
[28 of 36] Compiling Data.Generics.Product ( src/Data/Generics/Product.hs, dist/build/Data/Generics/Product.o )
[29 of 36] Compiling Data.Generics.Sum.Internal.Constructors ( src/Data/Generics/Sum/Internal/Constructors.hs, dist/build/Data/Generics/Sum/Internal/Constructors.o )
[30 of 36] Compiling Data.Generics.Sum.Constructors ( src/Data/Generics/Sum/Constructors.hs, dist/build/Data/Generics/Sum/Constructors.o )
[31 of 36] Compiling Data.Generics.Sum.Internal.Typed ( src/Data/Generics/Sum/Internal/Typed.hs, dist/build/Data/Generics/Sum/Internal/Typed.o )
[32 of 36] Compiling Data.Generics.Sum.Internal.Subtype ( src/Data/Generics/Sum/Internal/Subtype.hs, dist/build/Data/Generics/Sum/Internal/Subtype.o )
[33 of 36] Compiling Data.Generics.Sum.Subtype ( src/Data/Generics/Sum/Subtype.hs, dist/build/Data/Generics/Sum/Subtype.o )
[34 of 36] Compiling Data.Generics.Sum.Typed ( src/Data/Generics/Sum/Typed.hs, dist/build/Data/Generics/Sum/Typed.o )
[35 of 36] Compiling Data.Generics.Sum.Any ( src/Data/Generics/Sum/Any.hs, dist/build/Data/Generics/Sum/Any.o )
[36 of 36] Compiling Data.Generics.Sum ( src/Data/Generics/Sum.hs, dist/build/Data/Generics/Sum.o )
Preprocessing test suite 'generic-lens-bifunctor' for generic-lens-1.0.0.0..
Building test suite 'generic-lens-bifunctor' for generic-lens-1.0.0.0..
[1 of 1] Compiling Main             ( test/Bifunctor.hs, dist/build/generic-lens-bifunctor/generic-lens-bifunctor-tmp/Main.o )
Linking dist/build/generic-lens-bifunctor/generic-lens-bifunctor ...
Preprocessing test suite 'generic-lens-test' for generic-lens-1.0.0.0..
Building test suite 'generic-lens-test' for generic-lens-1.0.0.0..
[1 of 5] Compiling Test24           ( test/Test24.hs, dist/build/generic-lens-test/generic-lens-test-tmp/Test24.o )
[2 of 5] Compiling Test25           ( test/Test25.hs, dist/build/generic-lens-test/generic-lens-test-tmp/Test25.o )
[3 of 5] Compiling Test40           ( test/Test40.hs, dist/build/generic-lens-test/generic-lens-test-tmp/Test40.o )
[4 of 5] Compiling Util             ( test/Util.hs, dist/build/generic-lens-test/generic-lens-test-tmp/Util.o )
[5 of 5] Compiling Main             ( test/Spec.hs, dist/build/generic-lens-test/generic-lens-test-tmp/Main.o )
Linking dist/build/generic-lens-test/generic-lens-test ...
Preprocessing test suite 'generic-lens-syb-tree' for generic-lens-1.0.0.0..
Building test suite 'generic-lens-syb-tree' for generic-lens-1.0.0.0..
[1 of 1] Compiling Main             ( test/syb/Tree.hs, dist/build/generic-lens-syb-tree/generic-lens-syb-tree-tmp/Main.o )
Linking dist/build/generic-lens-syb-tree/generic-lens-syb-tree ...
Preprocessing test suite 'generic-lens-examples' for generic-lens-1.0.0.0..
Building test suite 'generic-lens-examples' for generic-lens-1.0.0.0..
[1 of 1] Compiling Main             ( examples/Biscuits.hs, dist/build/generic-lens-examples/generic-lens-examples-tmp/Main.o )
Linking dist/build/generic-lens-examples/generic-lens-examples ...
> /tmp/stackage-build11/generic-lens-1.0.0.0$ dist/build/generic-lens-examples/generic-lens-examples
hello
> /tmp/stackage-build11/generic-lens-1.0.0.0$ dist/build/generic-lens-test/generic-lens-test

Cases: 14  Tried: 0  Errors: 0  Failures: 0
Cases: 14  Tried: 1  Errors: 0  Failures: 0
Cases: 14  Tried: 2  Errors: 0  Failures: 0
Cases: 14  Tried: 3  Errors: 0  Failures: 0
                                           
### Failure in: 3
test/Util.hs:10
test/Spec.hs:222:7: subtypeLensManual === subtypeLensGeneric failed:
    LHS:
        $s$fSubtypeba_$csuper
        $s$fSubtypeba_$csuper = subtypeLensGeneric
        
        subtypeLensManual
        subtypeLensManual = $s$fSubtypeba_$csuper
        
    RHS:

Cases: 14  Tried: 4  Errors: 0  Failures: 1
Cases: 14  Tried: 5  Errors: 0  Failures: 1
Cases: 14  Tried: 6  Errors: 0  Failures: 1
Cases: 14  Tried: 7  Errors: 0  Failures: 1
                                           
### Failure in: 7
test/Util.hs:10
test/Spec.hs:226:7: sum1PrismManual === sum1PrismB failed:
    LHS:
        sum1PrismManual
        sum1PrismManual
          = \ @ p @ f $dChoice_ardO $dApplicative_ardP eta ->
              let {
                $dFunctor
                $dFunctor = $p1Applicative $dApplicative_ardP } in
              dimap
                ($p1Choice $dChoice_ardO)
                (\ x ->
                   case x of wild_X4A {
                     __DEFAULT -> Left (pure $dApplicative_ardP wild_X4A);
                     B i -> Right i
                   })
                (\ ds1 ->
                   case ds1 of {
                     Left x -> x;
                     Right y -> fmap $dFunctor B y
                   })
                (right' $dChoice_ardO eta)
        
    RHS:
        sum1PrismB
        sum1PrismB
          = \ @ p @ f $dChoice_ar97 $dApplicative_ar98 eta ->
              let {
                $dFunctor
                $dFunctor = $p1Applicative $dApplicative_ar98 } in
              dimap
                ($p1Choice $dChoice_ar97)
                (\ x ->
                   join {
                     $j_sy30
                     $j_sy30 x1
                       = Left
                           (pure
                              $dApplicative_ar98
                              (case x1 of {
                                 Left x1 ->
                                   case x1 of {
                                     L1 ds_dv3r ->
                                       case ds_dv3r of {
                                         L1 ds_dv3s -> A (ds_dv3s `cast` <Co:51>);
                                         R1 ds_dv3v -> B (ds_dv3v `cast` <Co:51>)
                                       };
                                     R1 ds_dv3y ->
                                       case ds_dv3y of {
                                         L1 ds_dv3z -> C (ds_dv3z `cast` <Co:51>);
                                         R1 ds_dv3C -> D (ds_dv3C `cast` <Co:51>)
                                       }
                                   };
                                 Right y ->
                                   case y of {
                                     L1 ds_dv3s -> A (ds_dv3s `cast` <Co:51>);
                                     R1 ds_dv3v -> B (ds_dv3v `cast` <Co:51>)
                                   }
                               })) } in
                   case x of {
                     A g1 -> jump $j_sy30 (Right (L1 (g1 `cast` <Co:54>)));
                     B g1 -> Right g1;
                     C g1 -> jump $j_sy30 (Left (R1 (L1 (g1 `cast` <Co:54>))));
                     D g1 -> jump $j_sy30 (Left (R1 (R1 (g1 `cast` <Co:54>))))
                   })
                (\ ds1 ->
                   case ds1 of {
                     Left x -> x;
                     Right y -> fmap $dFunctor B y
                   })
                (right' $dChoice_ar97 eta)
        

Cases: 14  Tried: 8  Errors: 0  Failures: 2
Cases: 14  Tried: 9  Errors: 0  Failures: 2
Cases: 14  Tried: 10  Errors: 0  Failures: 2
Cases: 14  Tried: 11  Errors: 0  Failures: 2
                                            
### Failure in: 11
test/Util.hs:10
test/Spec.hs:230:7: sum1PrismManualChar === sum1TypePrismChar failed:
    LHS:
        sum1PrismManualChar
        sum1PrismManualChar
          = \ @ p @ f $dChoice_arda $dApplicative_ardb eta ->
              let {
                $dFunctor
                $dFunctor = $p1Applicative $dApplicative_ardb } in
              dimap
                ($p1Choice $dChoice_arda)
                (\ x ->
                   case x of wild_X4B {
                     A i -> Right i;
                     B ds_duYQ -> Left (pure $dApplicative_ardb wild_X4B);
                     C ds_duYR -> Left (pure $dApplicative_ardb wild_X4B);
                     D ds_duYS -> Left (pure $dApplicative_ardb wild_X4B)
                   })
                (\ ds1 ->
                   case ds1 of {
                     Left x -> x;
                     Right y -> fmap $dFunctor A y
                   })
                (right' $dChoice_arda eta)
        
    RHS:
        sum1TypePrismChar
        sum1TypePrismChar
          = \ @ p @ f $dChoice_ar8o $dApplicative_ar8p eta_B1 ->
              let {
                $dFunctor
                $dFunctor = $p1Applicative $dApplicative_ar8p } in
              dimap
                ($p1Choice $dChoice_ar8o)
                (\ x ->
                   join {
                     $j_sy49
                     $j_sy49 x1
                       = Left
                           (pure
                              $dApplicative_ar8p
                              (case x1 of {
                                 Left x1 ->
                                   case x1 of {
                                     L1 ds_dv3r ->
                                       case ds_dv3r of {
                                         L1 ds_dv3s -> A (ds_dv3s `cast` <Co:51>);
                                         R1 ds_dv3v -> B (ds_dv3v `cast` <Co:51>)
                                       };
                                     R1 ds_dv3y ->
                                       case ds_dv3y of {
                                         L1 ds_dv3z -> C (ds_dv3z `cast` <Co:51>);
                                         R1 ds_dv3C -> D (ds_dv3C `cast` <Co:51>)
                                       }
                                   };
                                 Right y ->
                                   case y of {
                                     L1 ds_dv3s -> A (ds_dv3s `cast` <Co:51>);
                                     R1 ds_dv3v -> B (ds_dv3v `cast` <Co:51>)
                                   }
                               })) } in
                   case x of {
                     A g1 -> Right g1;
                     B g1 -> jump $j_sy49 (Right (R1 (g1 `cast` <Co:54>)));
                     C g1 -> jump $j_sy49 (Left (R1 (L1 (g1 `cast` <Co:54>))));
                     D g1 -> jump $j_sy49 (Left (R1 (R1 (g1 `cast` <Co:54>))))
                   })
                (\ ds1 ->
                   case ds1 of {
                     Left x -> x;
                     Right y -> fmap $dFunctor A y
                   })
                (right' $dChoice_ar8o eta_B1)
        

Cases: 14  Tried: 12  Errors: 0  Failures: 3
Cases: 14  Tried: 13  Errors: 0  Failures: 3
                                            
### Failure in: 13
test/Util.hs:10
test/Spec.hs:232:7: sum1PrismManual === sum1TypePrism failed:
    LHS:
        sum1PrismManual
        sum1PrismManual
          = \ @ p @ f $dChoice_ardO $dApplicative_ardP eta ->
              let {
                $dFunctor
                $dFunctor = $p1Applicative $dApplicative_ardP } in
              dimap
                ($p1Choice $dChoice_ardO)
                (\ x ->
                   case x of wild_X4A {
                     __DEFAULT -> Left (pure $dApplicative_ardP wild_X4A);
                     B i -> Right i
                   })
                (\ ds1 ->
                   case ds1 of {
                     Left x -> x;
                     Right y -> fmap $dFunctor B y
                   })
                (right' $dChoice_ardO eta)
        
    RHS:
        sum1TypePrism
        sum1TypePrism
          = \ @ p @ f $dChoice_ar8A $dApplicative_ar8B eta_B1 ->
              let {
                $dFunctor
                $dFunctor = $p1Applicative $dApplicative_ar8B } in
              dimap
                ($p1Choice $dChoice_ar8A)
                (\ x ->
                   join {
                     $j_sy3M
                     $j_sy3M x1
                       = Left
                           (pure
                              $dApplicative_ar8B
                              (case x1 of {
                                 Left x1 ->
                                   case x1 of {
                                     L1 ds_dv3r ->
                                       case ds_dv3r of {
                                         L1 ds_dv3s -> A (ds_dv3s `cast` <Co:51>);
                                         R1 ds_dv3v -> B (ds_dv3v `cast` <Co:51>)
                                       };
                                     R1 ds_dv3y ->
                                       case ds_dv3y of {
                                         L1 ds_dv3z -> C (ds_dv3z `cast` <Co:51>);
                                         R1 ds_dv3C -> D (ds_dv3C `cast` <Co:51>)
                                       }
                                   };
                                 Right y ->
                                   case y of {
                                     L1 ds_dv3s -> A (ds_dv3s `cast` <Co:51>);
                                     R1 ds_dv3v -> B (ds_dv3v `cast` <Co:51>)
                                   }
                               })) } in
                   case x of {
                     A g1 -> jump $j_sy3M (Right (L1 (g1 `cast` <Co:54>)));
                     B g1 -> Right g1;
                     C g1 -> jump $j_sy3M (Left (R1 (L1 (g1 `cast` <Co:54>))));
                     D g1 -> jump $j_sy3M (Left (R1 (R1 (g1 `cast` <Co:54>))))
                   })
                (\ ds1 ->
                   case ds1 of {
                     Left x -> x;
                     Right y -> fmap $dFunctor B y
                   })
                (right' $dChoice_ar8A eta_B1)
        
Cases: 14  Tried: 14  Errors: 0  Failures: 4
</details>

**Comment by kcsongor** [comment]
Thanks for reporting this, I’m investigating the cause
