### ISSUE TITLE
Add source links to documentation

### ISSUE THREAD

**Issue by Lysxia** [kcsongor/generic-lens#44]
It's quite useful to see the source code of a given identifier. Also, the documentation was uploaded manually. Did Hackage fail to build it? There are differences between the default settings of a local build and those of Hackage that are a bit distracting sometimes (like the "Contents" link at the top not linking to the homepage).

Thanks for this awesome package!

**Comment by kcsongor** [comment]
Thanks for pointing this out, I wasn't aware of the these differences!
Not sure what happened to the source links, but I've fixed them now, along with the "Contents" link (I had missed the `--for-hackage` flag for cabal).

Actually I uploaded the docs manually out of habit, as I had some problems in the past with hackage not building them, but I didn't wait long enough this time to see if that issue still persists.

Thanks again!
