### ISSUE TITLE
Getting support

### ISSUE THREAD

**Issue by newhoggy** [kcsongor/generic-lens#56]
For record types, need a way to express new getting fields not already in the type.  These are computed on access.  For example something like:

```
data Person = Person
  { firstname :: String
  , lastname :: String
  } deriving Generic

instance Getter "fullName" Record String where
  getter = to (\r -> (r ^. the @"field1") ++ " " ++ (r ^. the @"field2"))

...
let r = Person {..}
let fullName = r ^. the @"fullName"
```

**Comment by kcsongor** [comment]
You can provide manual instances for the `HasField` class, by marking the new instances `{-# OVERLAPPING #-}`

**Comment by kcsongor** [comment]
Feel free to reopen this issue if that doesn't work out!

**Comment by newhoggy** [comment]
Sorry, I may not have been clear.

I'm more concerned that `HasField` is must declare a lens, which must support both get and set, whereas the example I posted, a setter doesn't make sense, so `HasField` isn't suitable.

**Comment by kcsongor** [comment]
My bad, I see now. While I understand the usefulness of such a class, it seems like it is largely orthogonal to what generic-lens is concerned with, which is generically deriving these accessors, whereas I don't immediately see what kind of Getters would be derivable in this way (such that the corresponding Setters could not). Can you think of any examples?

**Comment by sboosali** [comment]
since you're manually defining the `fullName` getter anyway, why do you
want a pseudo-field `getter @"fullName"` at the type-level?
