### ISSUE TITLE
Export the IsInteresting typeclass from Data.Generics.Product.Types

### ISSUE THREAD

**Issue by kuribas** [kcsongor/generic-lens#61]
Is it possible to export the IsInteresting type family from Data.Generics.Product.Types?  It is interesting, if you forgive me the pun :-) I could use it to see if a type contains another type.
Perhaps rename it to something more descriptive, like HasSubType.

**Comment by kcsongor** [comment]
Certainly, I've been planning on doing this (see https://github.com/kcsongor/generic-lens/issues/39) just haven't got around to doing it yet. I have some plans for a new release in the coming week, so I'll make sure to do it too then!

**Comment by kcsongor** [comment]
Done in 95d7f6afac71e7f02c6d6e166c8148ba64258fc4
