### ISSUE TITLE
Type error and missing Generic instances

### ISSUE THREAD

**Issue by jaccokrijnen** [kcsongor/generic-lens#63]
Hey Csongor! Here's a minimal example of an issue I had when using `Data.Generics.Product.Types`

```haskell
data Record = Record {field1 :: Word32, field2 :: Int}
    deriving (Generic, Show)

x = over (types @Int) (+1) (Record 0 0)
```

Gives
```
error:
    • No instance for (Data.Generics.Product.Types.HasTypes'
                         (Data.Generics.Product.Types.Snd
                            (Data.Generics.Product.Types.InterestingOr
                               (Data.Generics.Product.Types.Interesting'
                                  (Rep Word32) Int '[Word32, Record])
                               (M1
                                  S
                                  ('MetaSel
                                     ('Just "field2")
                                     'NoSourceUnpackedness
                                     'NoSourceStrictness
                                     'DecidedLazy)
                                  (Rec0 Int))
                               Int))
                         Record
                         Int)
        arising from a use of ‘types’
    • In the first argument of ‘over’, namely ‘(types @Int)’
      In the expression: over (types @Int) (+ 1) (Record 0 0)
      In an equation for ‘x’: x = over (types @Int) (+ 1) (Record 0 0)
```

So I came across this type of error in a huge record structure and it only became clear after digging into the implementation of `Interesting'` that the problem is `Word32` not having a `Generic` instance (this of course can happen with any type that doesn't have such instance), and so the type family does not reduce as `Rep Word32` does not reduce. I can't use standalone deriving for Word32 as it is an   opaque datatype. So for now I have used a `Data` SYB approach instead.

It would be nice if there was a way to check that the data and all the recursive fields are `Generic` and hiding the implementation details by avoiding the non-reducing type families.

Appreciating the library!

**Comment by kcsongor** [comment]
Hi @jaccokrijnen, sorry for not replying to this earlier, @Lysxia helpfully patched this issue, and I forgot about it :)

Unfortunately there's no way to check if any particular type is an instance of `Generic`, and as the associated `Rep` type family isn't actually constrained, the error messages leak out without ever mentioning anything about `Generic`.

That said, I may have a workaround for "catching" stuck type families and improving reported errors, so I'll see if that's workable.
