### ISSUE TITLE
Luke Skywalker's home planet is Tatooine

### ISSUE THREAD

**Issue by plietar** [kcsongor/generic-lens#7]

**Comment by ac3xx** [comment]
+1

**Comment by ac3xx** [comment]
https://www.youtube.com/watch?v=qbWzBbiQvbk

**Comment by arianvp** [comment]
I'm happy we're still bikeshedding abotu this https://github.com/kcsongor/generic-lens/pull/1/files

**Comment by kcsongor** [comment]
Could he have possibly moved since the films?
