### ISSUE TITLE
Allow users to somehow reference non-exported constraints

### ISSUE THREAD

**Issue by LightAndLight** [kcsongor/generic-lens#79]
There are some programs that I can't give a type signature, because the constraints I need to add to the signature are not exported by `generic-lens`. For example, with `Data.Generics.Product.Typed`:

```
theInt :: (Generic s, HasType Int s) => Lens' s Int
theInt = typed @Int
```

I can't finish this definition, because I can't reference `ErrorUnlessOne` and `HasTotalTypePSym`.

I think that just exporting these names would be unwieldy, so we could define a constraint synonym for them:

```
type HasTypeConstraints a s =
  ( ErrorUnlessOne a s (CollectTotalType a (Rep s))
  , GLens (HasTotalTypePSym a) (Rep s) (Rep s) a a
  )

 instance
  ( Generic s
  , HasTypeConstraints a s
  ) => HasType a s where
...
```

Then `HasTypeConstraints` can be exported  along with `HasType`.

Now my definition becomes:

```
theInt :: (Generic s, HasTypeConstraints Int s, HasType Int s) => Lens' s Int
theInt = typed @Int
```

Which should now compile.

---

What do you think? A similar approach would follow for all the classes. I'm happy to do the work if you think this is useful.

**Comment by Lysxia** [comment]
It seems you swapped `HasType Int s` in the signature of `theInt`. And that would indeed be equivalent to `HasTypeConstraints s Int`.

**Comment by LightAndLight** [comment]
Thanks, I've fixed it to be consistent with what's already in the library.

**Comment by Lysxia** [comment]
I meant that now `theInt` typechecks, which removes the motivation for `HasTypeConstraints`.

**Comment by LightAndLight** [comment]
How confusing- the initial example does in fact compile. I'll revisit this tomorrow and see what I'm missing. I definitely encountered a problem in this area.

**Comment by LightAndLight** [comment]
I'm busy with other things so I'm going to close this. If I come across the issue I'll re-open.
