### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by 3noch** [kcsongor/generic-lens#8]
I'd be thrilled to use this but I fear for performance a bit. Are there any benchmarks you could publish?

**Comment by kcsongor** [comment]
I will try to find some time to do benchmarks in the next couple days - it has been pointed out to me that the generated code (after STG) looks identical to the hand-written version though for some simple examples

**Comment by thepratt** [comment]
@kcsongor It's been more than a couple days? Can you update us?

**Comment by kcsongor** [comment]
Apologies, I forgot to update this issue!

There is now a benchmark in the `benchmarks` folder, but more importantly, the test suite now uses the [ghc-proofs](https://github.com/nomeata/ghc-proofs) library to prove that after optimisations, the generated lenses are the same as the one you would have written manually. (The manual lenses are also included in the test suite)

**Comment by 3noch** [comment]
Wow, fantastic!

**Comment by CGenie** [comment]
It's been more than 7 years since closing this issue, but I'm trying find the `ghc-proofs` or benchmarks code for this library, and it seems it's no longer here?

And this one https://github.com/mpickering/generic-lens-benchmarks seems to be quite old and unrelated?
