### ISSUE TITLE
HasAny/AsAny will have incompatible VTA behavior between GHC 8.6 and 8.8

### ISSUE THREAD

**Issue by RyanGlScott** [kcsongor/generic-lens#84]
GHC 8.8 tightens up the implementation of how it infers the visibilities of kind variable binders in class methods (see [this section](https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.8#kind-variable-visibility-in-poly-kinded-class-methods) of the GHC 8.8 Migration Guide). One consequence of this change is that the `the` method of `HasAny` will have a completely different visibility for the kind of `sel` in 8.8 than it currently does in 8.6. In GHC 8.6, the type of `the` is:

```haskell
λ> :type +v the
the
  :: forall {k} (sel :: k) s t a b.
     HasAny sel s t a b =>
     Data.Generics.Internal.VL.Lens.Lens s t a b
```

In GHC 8.8, however, the type of `the` is:

```haskell
λ> :type +v the
the
  :: forall k (sel :: k) s t a b.
     HasAny sel s t a b =>
     Data.Generics.Internal.VL.Lens.Lens s t a b
```

Notice that `k` (the kind of `sel`) is now available for visible type application! This is more correct than before, strictly speaking, since `k` was explicitly written in the definition of `HasAny`:

https://github.com/kcsongor/generic-lens/blob/cf20ae3a0f27d25edf97c79b6635f7c79c9bc941/src/Data/Generics/Product/Any.hs#L56

One unfortunate consequence of this change is that none of the `doctest` examples associated with the `HasAny` class will typecheck anymore:

```
λ> data Human = Human { name :: String, age :: Int, address :: String } deriving Generic
λ> human :: Human; human = Human "Tunyasz" 50 "London"
λ> human ^. the @Int

<interactive>:33:1: error:
    • Could not deduce (HasAny sel0 Human Human b b)
      from the context: HasAny sel Human Human b b
        bound by the inferred type for ‘it’:
                   forall {sel :: Int} {b}. HasAny sel Human Human b b => b
        at <interactive>:33:1-17
      The type variable ‘sel0’ is ambiguous
    • In the ambiguity check for the inferred type for ‘it’
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      When checking the inferred type
        it :: forall {sel :: Int} {b}. HasAny sel Human Human b b => b
```

The `AsAny` class has a similar issue with its `_As` method:

https://github.com/kcsongor/generic-lens/blob/cf20ae3a0f27d25edf97c79b6635f7c79c9bc941/src/Data/Generics/Sum/Any.hs#L64

I can envision two possible ways of fixing this:

1. Make the following change to `HasAny`:

   ```diff
   diff --git a/src/Data/Generics/Product/Any.hs b/src/Data/Generics/Product/Any.hs
   index cc90fc0..e78bcf9 100644
   --- a/src/Data/Generics/Product/Any.hs
   +++ b/src/Data/Generics/Product/Any.hs
   @@ -53,7 +53,7 @@ import Data.Generics.Product.Typed
    -- human = Human "Tunyasz" 50 "London"
    -- :}
    
   -class HasAny (sel :: k) s t a b | s sel k -> a where
   +class HasAny sel s t a b | s sel -> a where
      -- |A lens that focuses on a part of a product as identified by some
      --  selector. Currently supported selectors are field names, positions and
      --  unique types. Compatible with the lens package's 'Control.Lens.Lens'
   ```

   Then `k` will revert back to being inferred, not specified, and `human ^. the @Int` will continue to work. (This is backwards compatible with old GHCs as well.)
2. Pass an extra `@_` argument to `the`:

   ```
   λ> human ^. the @_ @Int
   50
   ```

   (This is not backwards-compatible with old GHCs.)

**Comment by mpickering** [comment]
I don't think this change is very satisfactory overall as fix 1 works fine if you are polymorphic over all `k` but I think it will break a program like:

```
class Foo (a : [k]) b where
   ...
```

Fix 2 isn't an option as it changes the public API.

**Comment by RyanGlScott** [comment]
I'm not sure that I understand your concern about option 1. Neither `HasAny` nor `AsAny` have any fields of the form `(a :: [k])`, so this shouldn't be a problem here, yes?

**Comment by phadej** [comment]
I wonder why it has to be (sel :: k), isn't `sel` always `Symbol` ?

**Comment by phadej** [comment]
Silly me:

> Currently supported selectors are field names, positions and unique types

**Comment by phadej** [comment]
@RyanGlScott is there a way to introduce a kind variable, without allowing it to be usable for `TypeApplications`? IMHO this is regression in 8.8, not a "more correct". As a library writer I'd like to write

```
class HasAny (sel :: k) (s :: Type) (t :: Type) (a :: Type) (b :: Type) where
```

because I like explicit kind annotations. Now if `k` becomes visible for application, I cannot be as explicit as I want! So I have to write

```
class HasAny sel (s :: Type) (t :: Type) (a :: Type) (b :: Type) where
```

and **hope** that GHC kind-inference does the right thing.

**Comment by RyanGlScott** [comment]
> IMHO this is regression in 8.8, not a "more correct".

To see how broken the situation was before GHC 8.8, consider these two examples (taken from the GHC 8.8 Migration Guide):

```haskell
class C1 (a :: k) b where
  p1 :: Proxy a -> Proxy b

class C2 (a :: k) (b :: Type) where
  p2 :: Proxy a -> Proxy b
```

In GHC 8.6 and earlier, the kind of `a` is specified (i.e., available for visible type application) in `p2`, but _not_ in `p1`!

```
λ> :type +v p1
p1
  :: forall {k1} {k2} (a :: k1) (b :: k2).
     C1 a b =>
     Proxy a -> Proxy b
λ> :type +v p2
p2 :: forall k (a :: k) b. C2 a b => Proxy a -> Proxy b
```

This is because GHC did visibility inference for classes with **c**omplete **u**ser-**s**pecified **k**inds (CUSKs) in a completely different way than classes without CUSKs. (`C1` doesn't have a CUSK, whereas `C2` does.) GHC 8.8 tightened this up so that visibility inference now works the same regardless of whether the class has a CUSK or not—if you explicitly write out a kind variable like `k`, then it's specified.

This is consistent with the way visibility inference works in other top-level declarations (such as functions). Alas, it turns out that there is code in the wild (such as in `generic-lens`) that took advantage of the previous buggy behavior for CUSK-less classes, and that code will have to be updated. It's unfortunate, but this code only ever typechecked in the first place due to a lucky fluke.

**Comment by mpickering** [comment]
> I'm not sure that I understand your concern about option 1. Neither `HasAny` nor `AsAny` have any type variable binders of the form `(a :: [k])`, so this shouldn't be a problem here, yes?

No, it's fine here but a general point about why this change is problematic. 

In your first example if you want to make `k` available then you could explicitly quantify it. Now there is no way to make `k` invisible and inferred from `a`. So the previous broken state could be argued to be better.

```
class forall k a b . C1 (a :: k) b where
  p1 :: Proxy a -> Proxy b
```

**Comment by RyanGlScott** [comment]
In response to @phadej's other question in https://github.com/kcsongor/generic-lens/issues/84#issuecomment-463164575 (and the question that @mpickering is implicitly asking in https://github.com/kcsongor/generic-lens/issues/84#issuecomment-463097948 and https://github.com/kcsongor/generic-lens/issues/84#issuecomment-463167753):

> is there a way to introduce a kind variable, without allowing it to be usable for `TypeApplications`?

While there's no direct way to do this in the language, there is an _indirect_ way: use constraint synonyms. For instance, say you want to define this function, but avoid `k` from being specified for VTA:

```haskell
foo :: forall k (a :: [k]). Proxy a
foo = Proxy
```

You can define a constraint synonym for this purpose:

```haskell
type HasListKind (a :: [k]) = (() :: Constraint)
```

Then you can redefine `foo` like so:

```haskell
foo :: forall a. HasListKind a => Proxy a
foo = Proxy
```

This will give you the desired visibility for `k`:

```
λ> :type +v foo
foo :: forall {k} (a :: [k]). HasListKind a => Proxy a
```

It's a bit clunky, but it's a serviceable workaround until something like [this proposal](https://github.com/ghc-proposals/ghc-proposals/pull/99) is implemented.

**Comment by mpickering** [comment]
ok that sounds good then. Thanks for bringing it to our attention.

**Comment by kcsongor** [comment]
Thanks, glad to know this has been fixed!

The original purpose of the kind signature was that it made the fundep easier to read, and make the whole thing seem less magical.
