### ISSUE TITLE
Needs a version bump

### ISSUE THREAD

**Issue by ddssff** [kcsongor/generic-lens#92]
The version in github has a lot of changes not available in hackage, it would be nice to bump the version so we could indicate that something won't build with the hackage version.

**Comment by ddssff** [comment]
A new hackage release is another good option.

**Comment by mpickering** [comment]
I asked @kcsongor if he could do a release.

**Comment by kcsongor** [comment]
The wait is finally over! http://hackage.haskell.org/package/generic-lens
